apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-service-config
data:
  db.url: jdbc:postgresql://postgres:5432/user_auth_db
  redis.host: redis
  redis.port: "6379"
  keycloak.url: http://keycloak:8080
  keycloak.realm: user-auth
  keycloak.client: user-auth-client 