apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  labels:
    app: user-auth-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: user-auth-service 